dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3
protocols = imap
listen = *

auth_allow_cleartext = yes
auth_allow_weak_schemes = yes
auth_mechanisms = plain login
default_internal_group = vmail
default_internal_user = vmail
default_login_user = vmail

mail_driver = maildir
mail_home = /srv/mail/%{user}
mail_path = ~/Maildir
mail_uid = vmail
mail_gid = vmail
ssl = no
first_valid_uid = 1

passdb passwd-file {
  passwd_file_path = /etc/dovecot/users
}

userdb static {
  allow_all_users = yes
  fields {
    uid = vmail
    gid = vmail
    home = /srv/mail/%{user}
  }
}

service imap-login {
  inet_listener imap {
    port = 31143
  }

  inet_listener imaps {
    port = 0
  }
}
